# Be sure to restart your server when you modify this file.

secrets: &secrets
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fitbit_key: <%= ENV["FITBIT_KEY"] %>
  fitbit_secret: <%= ENV["FITBIT_SECRET"] %>

development:
  <<: *secrets

test:
  <<: *secrets

production:
  <<: *secrets
