# Be sure to restart your server when you modify this file.

secrets: &secrets
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fitbit_key: <%= ENV["FITBIT_KEY"] %>
  fitbit_secret: <%= ENV["FITBIT_SECRET"] %>
  admin_user: <%= ENV["ADMIN_USER"] %>
  admin_pass: <%= ENV["ADMIN_PASS"] %>
  zero_push_auth_token: <%= ENV["ZERO_PUSH_AUTH_TOKEN"] %>

development:
  <<: *secrets

test:
  <<: *secrets

production:
  <<: *secrets
